"""The favicon set must exist, be valid, and be referenced by every page.

Icons are generated by tools/make_icons.py and committed, because the site has no
build step and no image dependency. A regenerated icon that silently produces a
malformed ICO would show as a blank tab, which no other test would catch.
"""
from __future__ import annotations

import json
import struct
import unittest

from ballast import config

DOCS = config.ROOT / "docs"
PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def png_size(data: bytes) -> tuple[int, int]:
    assert data[:8] == PNG_SIGNATURE and data[12:16] == b"IHDR"
    return struct.unpack(">II", data[16:24])


class TestIconFiles(unittest.TestCase):
    def test_the_set_exists(self):
        for name in ("favicon.ico", "favicon.svg", "apple-touch-icon.png",
                     "icon-192.png", "icon-512.png", "site.webmanifest"):
            self.assertTrue((DOCS / name).exists(), f"{name} is missing")

    def test_ico_is_well_formed_and_multi_size(self):
        data = (DOCS / "favicon.ico").read_bytes()
        reserved, kind, count = struct.unpack("<HHH", data[:6])
        self.assertEqual((reserved, kind), (0, 1), "not an icon file")
        self.assertGreaterEqual(count, 3, "needs 16/32/48 for crisp tabs")
        sizes = []
        for i in range(count):
            w, h, _, _, _, _, length, offset = struct.unpack(
                "<BBBBHHII", data[6 + i * 16: 22 + i * 16])
            self.assertEqual(data[offset:offset + 8], PNG_SIGNATURE,
                             f"entry {i} is not a PNG")
            self.assertEqual(png_size(data[offset:offset + length]),
                             (w or 256, h or 256), f"entry {i} size mismatch")
            sizes.append(w or 256)
        self.assertEqual(sorted(sizes), [16, 32, 48])

    def test_pngs_are_the_declared_size(self):
        for name, expected in [("apple-touch-icon.png", 180),
                               ("icon-192.png", 192), ("icon-512.png", 512)]:
            self.assertEqual(png_size((DOCS / name).read_bytes()), (expected, expected), name)

    def test_svg_is_scalable_and_carries_the_brand_colour(self):
        svg = (DOCS / "favicon.svg").read_text()
        self.assertIn("viewBox", svg, "a favicon without a viewBox will not scale")
        self.assertIn("#00d9ec", svg)

    def test_manifest_is_valid_and_points_at_real_files(self):
        manifest = json.loads((DOCS / "site.webmanifest").read_text())
        self.assertEqual(manifest["name"], "Ballast")
        for icon in manifest["icons"]:
            self.assertTrue((DOCS / icon["src"]).exists(), icon["src"])

    def test_every_page_references_the_icons(self):
        for page in DOCS.glob("*.html"):
            html = page.read_text()
            for tag in ('href="favicon.ico"', 'href="favicon.svg"',
                        'href="apple-touch-icon.png"', 'href="site.webmanifest"',
                        'name="theme-color"'):
                self.assertIn(tag, html, f"{page.name} is missing {tag}")

    def test_icons_are_regenerated_identically(self):
        """A committed artifact must match what the generator produces."""
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            "make_icons", config.ROOT / "tools" / "make_icons.py")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        self.assertEqual(module.ico([16, 32, 48]), (DOCS / "favicon.ico").read_bytes())
        self.assertEqual(module.png(180), (DOCS / "apple-touch-icon.png").read_bytes())


if __name__ == "__main__":
    unittest.main()
