venue:
  name: BITGET
  account_type: MARGIN
  oms_type: NETTING
  starting_balances:
  - amount: 100000
    currency: USDT
strategy:
  module: strategy
  class: OvernightProtectionStrategy
  config_class: OvernightProtectionConfig
  config:
    order_id_tag: '001'
    trade_size: '1'
    event_dates:
      ORCLUSDT: '2026-09-10'
      ADBEUSDT: '2026-09-10'
      NVDAUSDT: '2026-08-26'
      TSLAUSDT: '2026-07-22'
      PLTRUSDT: '2026-08-03'
      COINUSDT: '2026-07-30'
      AMDUSDT: '2026-08-04'
      MSFTUSDT: '2026-07-29'
      MUUSDT: '2026-06-24'
      NKEUSDT: '2026-06-30'
instruments:
- id: ORCLUSDT.BITGET
  kind: perpetual
  raw_symbol: ORCLUSDT
  base_currency: ORCL
  quote_currency: USDT
  settlement_currency: USDT
  price_precision: 4
  size_precision: 2
  price_increment: '0.0001'
  size_increment: '0.01'
  lot_size: '0.01'
  maker_fee: '0.0002'
  taker_fee: '0.0006'
  bar_type: ORCLUSDT.BITGET-1-HOUR-LAST-EXTERNAL
- id: ADBEUSDT.BITGET
  kind: perpetual
  raw_symbol: ADBEUSDT
  base_currency: ADBE
  quote_currency: USDT
  settlement_currency: USDT
  price_precision: 4
  size_precision: 2
  price_increment: '0.0001'
  size_increment: '0.01'
  lot_size: '0.01'
  maker_fee: '0.0002'
  taker_fee: '0.0006'
  bar_type: ADBEUSDT.BITGET-1-HOUR-LAST-EXTERNAL
- id: NVDAUSDT.BITGET
  kind: perpetual
  raw_symbol: NVDAUSDT
  base_currency: NVDA
  quote_currency: USDT
  settlement_currency: USDT
  price_precision: 4
  size_precision: 2
  price_increment: '0.0001'
  size_increment: '0.01'
  lot_size: '0.01'
  maker_fee: '0.0002'
  taker_fee: '0.0006'
  bar_type: NVDAUSDT.BITGET-1-HOUR-LAST-EXTERNAL
- id: TSLAUSDT.BITGET
  kind: perpetual
  raw_symbol: TSLAUSDT
  base_currency: TSLA
  quote_currency: USDT
  settlement_currency: USDT
  price_precision: 4
  size_precision: 2
  price_increment: '0.0001'
  size_increment: '0.01'
  lot_size: '0.01'
  maker_fee: '0.0002'
  taker_fee: '0.0006'
  bar_type: TSLAUSDT.BITGET-1-HOUR-LAST-EXTERNAL
- id: PLTRUSDT.BITGET
  kind: perpetual
  raw_symbol: PLTRUSDT
  base_currency: PLTR
  quote_currency: USDT
  settlement_currency: USDT
  price_precision: 4
  size_precision: 2
  price_increment: '0.0001'
  size_increment: '0.01'
  lot_size: '0.01'
  maker_fee: '0.0002'
  taker_fee: '0.0006'
  bar_type: PLTRUSDT.BITGET-1-HOUR-LAST-EXTERNAL
- id: COINUSDT.BITGET
  kind: perpetual
  raw_symbol: COINUSDT
  base_currency: COIN
  quote_currency: USDT
  settlement_currency: USDT
  price_precision: 4
  size_precision: 2
  price_increment: '0.0001'
  size_increment: '0.01'
  lot_size: '0.01'
  maker_fee: '0.0002'
  taker_fee: '0.0006'
  bar_type: COINUSDT.BITGET-1-HOUR-LAST-EXTERNAL
- id: AMDUSDT.BITGET
  kind: perpetual
  raw_symbol: AMDUSDT
  base_currency: AMD
  quote_currency: USDT
  settlement_currency: USDT
  price_precision: 4
  size_precision: 2
  price_increment: '0.0001'
  size_increment: '0.01'
  lot_size: '0.01'
  maker_fee: '0.0002'
  taker_fee: '0.0006'
  bar_type: AMDUSDT.BITGET-1-HOUR-LAST-EXTERNAL
- id: MSFTUSDT.BITGET
  kind: perpetual
  raw_symbol: MSFTUSDT
  base_currency: MSFT
  quote_currency: USDT
  settlement_currency: USDT
  price_precision: 4
  size_precision: 2
  price_increment: '0.0001'
  size_increment: '0.01'
  lot_size: '0.01'
  maker_fee: '0.0002'
  taker_fee: '0.0006'
  bar_type: MSFTUSDT.BITGET-1-HOUR-LAST-EXTERNAL
- id: MUUSDT.BITGET
  kind: perpetual
  raw_symbol: MUUSDT
  base_currency: MU
  quote_currency: USDT
  settlement_currency: USDT
  price_precision: 4
  size_precision: 2
  price_increment: '0.0001'
  size_increment: '0.01'
  lot_size: '0.01'
  maker_fee: '0.0002'
  taker_fee: '0.0006'
  bar_type: MUUSDT.BITGET-1-HOUR-LAST-EXTERNAL
- id: NKEUSDT.BITGET
  kind: perpetual
  raw_symbol: NKEUSDT
  base_currency: NKE
  quote_currency: USDT
  settlement_currency: USDT
  price_precision: 4
  size_precision: 2
  price_increment: '0.0001'
  size_increment: '0.01'
  lot_size: '0.01'
  maker_fee: '0.0002'
  taker_fee: '0.0006'
  bar_type: NKEUSDT.BITGET-1-HOUR-LAST-EXTERNAL
execution:
  start: '2026-06-21'
  end: '2026-09-18'
